gather/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
import registration.backends.default.urls

urlpatterns = patterns('',
	url(r'^create/$', 'gather.views.create_event', name='gather_create_event'),
	url(r'^upcoming/$', 'gather.views.upcoming_events', name='gather_upcoming_events'),
	url(r'^guide/$', 'gather.views.event_guide', name='gather_event_guide'),
	url(r'^past/$', 'gather.views.past_events', name='gather_past_events'),
	url(r'^review/$', 'gather.views.needs_review', name='gather_needs_review'),
	url(r'^message/$', 'gather.emails.event_message', name='gather_event_message'),
	url(r'^newuser/$', 'gather.views.new_user_email_signup', name='gather_new_user_email_signup'),
	url(r'^emailpreferences/(?P<username>[\w\d\-\.@+_]+)/$', 'gather.views.email_preferences', name='gather_email_preferences'),
	url(r'^(?P<event_id>\d+)/(?P<event_slug>[\w\d\-\.@+_]+)/edit/$', 'gather.views.edit_event', name='gather_edit_event'),
	url(r'^(?P<event_id>\d+)/(?P<event_slug>[\w\d\-\.@+_]+)/rsvp/yes/newuser/$', 'gather.views.rsvp_new_user', name='gather_rsvp_new_user'),
	url(r'^(?P<event_id>\d+)/(?P<event_slug>[\w\d\-\.@+_]+)/rsvp/no/$', 'gather.views.rsvp_cancel', name='gather_rsvp_cancel'),
	url(r'^(?P<event_id>\d+)/(?P<event_slug>[\w\d\-\.@+_]+)/rsvp/yes/$', 'gather.views.rsvp_event', name='gather_rsvp_event'),
	url(r'^(?P<event_id>\d+)/(?P<event_slug>[\w\d\-\.@+_]+)/endorse/$', 'gather.views.endorse', name='gather_event_endorse'),
	url(r'^(?P<event_id>\d+)/(?P<event_slug>[\w\d\-\.@+_]+)/publish/$', 'gather.views.event_publish', name='gather_event_publish'),
	url(r'^(?P<event_id>\d+)/(?P<event_slug>[\w\d\-\.@+_]+)/approve/$', 'gather.views.event_approve', name='gather_event_approve'),
	url(r'^(?P<event_id>\d+)/(?P<event_slug>[\w\d\-\.@+_]+)/$', 'gather.views.view_event', name='gather_view_event'),
)

gather/models.py
from django.db import models
from django.contrib.auth.models import User, Group
from PIL import Image
import uuid, os, datetime
from django.conf import settings
from django.db.models.signals import post_save
import requests
from django.utils import timezone

class EventAdminGroup(models.Model):
	''' Define admininstrative groups per location.'''
	location = models.ForeignKey(settings.LOCATION_MODEL, unique=True)
	users = models.ManyToManyField(User)

	def __unicode__(self):
		return self.location.name + " Admin Group"

	class Meta:
		app_label = 'gather'

class EventSeries(models.Model):
	''' Events may be associated with a series. A series has a name and
	desciption, and its own landing page which lists the associated events. '''
	name = models.CharField(max_length=200)
	description = models.TextField()

	def __unicode__(self):
		return self.name

	class Meta:
		app_label = 'gather'

class Location(models.Model):
	''' A stub location model to support basic location-based functionality.
	Most people will write their own location model (either extending this one,
	or using a model from another app). Django-gather is designed only to rely
	on the 'slug' Location field, and the ability to associate events with a
	location object (ie, a primary key).
	django-gather requires settings.py to include a setting named
	LOCATION_MODEL. The default is LOCATION_MODEL = gather.Location, which is
	this model."
	'''
	name = models.CharField(max_length=200)
	slug = models.CharField(max_length=60, unique=True)

	def __unicode__(self):
		return self.name

	class Meta:
		app_label = 'gather'

def event_img_upload_to(instance, filename):
	ext = filename.split('.')[-1]
	# rename file to random string
	filename = "%s.%s" % (uuid.uuid4(), ext.lower())

	upload_path = "events/"
	upload_abs_path = os.path.join(settings.MEDIA_ROOT, upload_path)
	if not os.path.exists(upload_abs_path):
		os.makedirs(upload_abs_path)
	return os.path.join(upload_path, filename)

class EventManager(models.Manager):
	def upcoming(self, upto=None, current_user=None, location=None):
		# return the events happening today or in the future, returning up to
		# the number of events specified in the 'upto' argument.
		today = timezone.now()
		print today

		upcoming = super(EventManager, self).get_query_set().filter(end__gte = today).exclude(status=Event.CANCELED).order_by('start')
		if location:
			upcoming = upcoming.filter(location=location)
		viewable_upcoming = []
		for event in upcoming:
			if event.is_viewable(current_user):
				viewable_upcoming.append(event)
				if upto and len(viewable_upcoming) == upto:
					break
		print viewable_upcoming
		return viewable_upcoming

	class Meta:
		app_label = 'gather'

# Create your models here.
class Event(models.Model):
	PENDING = 'waiting for approval'
	FEEDBACK = 'seeking feedback'
	READY = 'ready to publish'
	LIVE = 'live'
	CANCELED = 'canceled'

	event_statuses = (
			(PENDING, 'Waiting for Approval'),
			(FEEDBACK, 'Seeking Feedback'),
			(READY, 'Ready to publish'),
			(LIVE, 'Live'),
			(CANCELED, 'Canceled'),
	)

	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	start = models.DateTimeField(verbose_name="Start time")
	end = models.DateTimeField(verbose_name="End time")
	title = models.CharField(max_length=300)
	slug = models.CharField(max_length=60, help_text="This will be auto-suggested based on the event title, but feel free to customize it.", unique=True)
	description = models.TextField(help_text="Basic HTML markup is supported for your event description.")
	image = models.ImageField(upload_to=event_img_upload_to)
	attendees = models.ManyToManyField(User, related_name="events_attending", blank=True, null=True)
	notifications = models.BooleanField(default = True)
	# where, site, place, venue
	where = models.CharField(verbose_name = 'Where will the event be held?', max_length=500, help_text="Either a specific room at this location or an address if elsewhere")
	creator = models.ForeignKey(User, related_name="events_created")
	organizers = models.ManyToManyField(User, related_name="events_organized", blank=True, null=True)
	organizer_notes = models.TextField(blank=True, null=True, help_text="These will only be visible to other organizers")
	limit = models.IntegerField(default=0, help_text="Specify a cap on the number of RSVPs, or 0 for no limit.", blank=True)
	# public events can be seen by anyone, private events can only be seen by organizers and attendees.
	private = models.BooleanField(default=False, help_text="Private events will only be seen by organizers, attendees, and those who have the link. It will not be displayed in the public listing.")
	status = models.CharField(choices = event_statuses, default=PENDING, max_length=200, verbose_name='Review Status', blank=True)
	endorsements = models.ManyToManyField(User, related_name="events_endorsed", blank=True, null=True)
	# the location field is optional but lets you associate an event with a
	# specific location object that is also managed by this software. a single
	# location or multiple locations can be defined.
	location = models.ForeignKey(settings.LOCATION_MODEL)
	series = models.ForeignKey(EventSeries, related_name='events', blank=True, null=True)
	admin = models.ForeignKey(EventAdminGroup, related_name='events')

	objects = EventManager()

	def __unicode__(self):
		return self.title

	class Meta:
		app_label = 'gather'

	def is_viewable(self, current_user):
		# an event is viewable only if it's both live and public, or the
		# current_user is an event admin, created the event, or is an attendee
		# or organizer. 
		if (self.admin and current_user) and (current_user in self.admin.users.all()):
			is_event_admin = True
		else:
			is_event_admin = False
		if ((self.status == 'live' and self.private == False) or (is_event_admin or
				current_user == self.creator or current_user in self.organizers.all() or
				current_user in self.attendees.all())):
			viewable = True
		else:
			viewable = False
		return viewable

def default_event_status(sender, instance, created, using, **kwargs):
	print instance
	print created
	print instance.status
	if created == True:
		if instance.creator in instance.admin.users.all():
			instance.status = Event.FEEDBACK
		else:
			instance.status = Event.PENDING
post_save.connect(default_event_status, sender=Event)

class EventNotifications(models.Model):
	user = models.OneToOneField(User, related_name='event_notifications')
	# send reminders on day-of the event?
	reminders = models.BooleanField(default=True)
	# receive weekly announcements about upcoming events?
	location_weekly = models.ManyToManyField(settings.LOCATION_MODEL, related_name="")

	class Meta:
		app_label = 'gather'

User.event_notifications = property(lambda u: EventNotifications.objects.get_or_create(user=u)[0])

# override the save method of the User model to create the EventNotifications
# object automatically for new users
def add_user_event_notifications(sender, instance, created, using, **kwargs):
	# just accessing the field will create the object, since the field is
	# defined with get_or_create, above.
	instance.event_notifications
	return

# I don't think this is needed because of the get_or_create we are using.
# This causes problems when we dump and load data so I'm turning it off --JLS
# post_save.connect(add_user_event_notifications, sender=User)

gather/templates/gather_event_create.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}

{% if messages %}
<div class="messages">
	{% for message in messages %}
	<div class="alert alert-info">
		<button type="button" class="close" data-dismiss="alert">×</button>
		<div {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</div>
	</div>
	{% endfor %}
</div>
{% endif %}


<div id="event-preamble">
	{% if not is_event_admin %}
		{% include 'snippets/event_hosting_info.html' %}
	{% else %}
		{% include 'snippets/event_admin_info.html' %}
	{% endif %}
</div>

<div class="col-md-8">

	<form class="form-horizontal" enctype="multipart/form-data" method="post" action="{% url 'gather_create_event' location.slug %}">{% csrf_token %}
		{% include "snippets/event_form_body.html" %}
		<input id="submit-event" type="submit" class="btn btn-lg" value="Submit Event">
	</form>
</div>
<div class="col-md-4">
</div>

{% endblock %}

{% block extrajs %}
<script type="text/javascript" src="{% static 'js/jquery-ui-timepicker-addon.js' %}"></script>
<script>

	{% include "snippets/js/organizers_autocomplete.js" %}

	$('#id_start').datetimepicker({
		controlType: 'select'
	});	
	$('#id_end').datetimepicker({
		controlType: 'select'
	});

	clean_slug_value = function(e) {
		// make sure there's only letters, numbers and hyphens by removing
		// special characters, and replace spaces with hyphens (making sure
		// only one hyphen in a row). force the slug to lowercase. 
		str = $(e.data.elem_id).val();
		slugified = str.replace(/[^\d\w\- ]/g, "").replace(/ /g,"-").replace(/-{2,}/, "-").toLowerCase();

		// check max length
		if (slugified.length > 50) {
			slugified = slugified.substring(0,50);
		}
		// make sure there's no trailing hyphens (after trimming, because that
		// will change the last character)
		slugified = slugified.replace(/-$/, "");
		$("#id_slug").val(slugified);
		return false;
	};

	$("#id_title").on('input', {'elem_id': "#id_title"}, clean_slug_value);
	$("#id_slug").focusout({'elem_id': "#id_slug"}, clean_slug_value)


</script>
{% endblock %}

gather/templates/gather_event_edit.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}

<form class="form-horizontal" enctype="multipart/form-data" method="post" action="{% url 'gather_edit_event' location.slug event_id event_slug %}">{% csrf_token %}
	{% include "snippets/event_form_body.html" %}
	<input id="submit-event" type="submit" class="btn" value="Submit">
</form>

{% endblock %}

{% block extrajs %}
<script type="text/javascript" src="{% static 'js/jquery-ui-timepicker-addon.js' %}"></script>
<script>

	{% include "snippets/js/organizers_autocomplete.js" %}

	$('#id_start').datetimepicker({
		controlType: 'select'
	});	
	$('#id_end').datetimepicker({
		controlType: 'select'
	});

	clean_slug_value = function(e) {
		// make sure there's only letters, numbers and hyphens by removing
		// special characters, and replace spaces with hyphens (making sure
		// only one hyphen in a row). force the slug to lowercase. 
		str = $(e.data.elem_id).val();
		slugified = str.replace(/[^\d\w\- ]/g, "").replace(/ /g,"-").replace(/-{2,}/, "-").toLowerCase();

		// check max length
		if (slugified.length > 50) {
			slugified = slugified.substring(0,50);
		}
		// make sure there's no trailing hyphens (after trimming, because that
		// will change the last character)
		slugified = slugified.replace(/-$/, "");
		$("#id_slug").val(slugified);
		return false;
	};

	$("#id_title").on('input', {'elem_id': "#id_title"}, clean_slug_value);
	$("#id_slug").focusout({'elem_id': "#id_slug"}, clean_slug_value)


</script>
{% endblock %}

gather/templates/gather_event_guide.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}

<h1>Event Hosting Guide</h1>

<h2 class="event-guide-title">Community Events</h2>
<div>
	We love to host creative and interesting events that are open to and enrich our community. Example of common and past events:
	<ul>
		<li>Meetups
		<li>Dinners
		<li>Hackathons
		<li>Speakers
		<li>Salons
		<li>Tastings
		<li>Workshops
		<li>Movie nights
		<li>Concerts
	</ul>

	Available for your event:
	<ul>
		<li>Giant freestanding screen (~4’ x 6’) and a projector
		<li>Dining room which can seat 20-30 easily
		<li>Living room can hold about 40, 50-60 with standing-room-only
		<li>Baby grand piano for performances
		<li>Kitchen for preparing food/snacks. We usually have some room to squeeze items that need refrigeration but not a ton. 
		<li>Downstairs movie area, seats 5-8 (movies can be shown on the big screen as well)
		<li>Serving platters, dishes and cutlery for about 60, wine glasses for about 40 (depending on where we are in the cycle of them breaking and being replaced) 
		<li>Speakers - we have one set of speakers that's often floating around the house either in the living room or on the lower level by the movie area. 
		<li>Lots of folding chairs - usually tucked away in a corner of the dining room or by the bottom of the main staircase on the ground floor. Some additional chairs also in the coworking area. 
		<li>Furniture - feel free to rearrange in particular the living and dining rooms as appropriate for your event; just put things back when you're done. 

	</ul>


	<h3>Hosting process</h3>
	<ul>
		<li><b>You are responsible for set up and spotless clean-up after.</b>
		<ul>
			<li>Putting back furniture
			<li>Washing and putting away all dishes from the event
			<li>Spot check for things left out or around. 
		</ul>
		<li>Supplies: You bring your own supplies of food and drink. You are welcome to use our dishes and plates. We have tons. 
		<li>Introduce yourself to people in the house. We have many residents and guests who are likely to attend and/or be around during setup or the event itself. 
		<li>Advertising: you are the host and so it’s up to you to decide how you want to promote the events. Many people use eventbrite.com or Facebook to track RSVPs and communicate with guests. If you would like us to advertise your event on our events list, Facebook or Twitter, we’d be very happy to. Please provide:
		<ul>
			<li>Date and time
			<li>Event description
			<li>An email announcement we can forward to our list
			<li>A Facebook post we can share
			<li>A Tweet we can retweet
		</ul>
	</ul>

	<h3>Pricing</h3>
		<ul>
			<li>Small free community events are free to host. 
			<li>If you are hosting a non-for-profit event but charging for tickets to cover costs, we ask for a $50 contribution to the house. This goes towards our costs of maintaining the space - we have cleaners regularly, extra garbage pickup to support events, and general upkeep/maintenance of furniture, glassware, electronics, and general tricked-out-ness to support awesome activities!
			<li>For-profit events are also welcome, but we ask for an appropriate revenue-share based on your event model.  
		</ul>
</div>

<h2 class="event-guide-title">Private Events</h2>
<div>
	We are also open to hosting private events if they advance a specific goal
	or aim in line with our community, or makes a meaningful financial
	contribution to house - which in turn goes towards supporting more open
	community events. Example:
	<ul>
		<li>Fundraisers
		<li>Special Company dinners
		<li>Courses
		<li>Wedding Showers
		<li>Small conferences and offsites
	</ul>
	Please contact us directly at <a href="mailto:events@embassynetwork.com">events@embassynetwork.com</a> to discuss your private event ideas! 
</div>

{% endblock %}

gather/templates/gather_event_view.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}

<meta property="og:image" content="https://{{domain}}{{ MEDIA_URL }}{{ event.image }}"/>
<meta property="og:title" content="{{event.title|title}}"/>
<meta property="og:url" content="https://{{domain}}/events/{{event.id}}/{{event.slug}}"/>
<meta property="og:description" content="{{event.description}}"/>

<div id="event-view-wrapper">
	<div class="modal fade" id="new-user-modal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-dialog-med">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h3 class="modal-title">Almost There...</h3>
			</div>
			<div class="modal-body">
				<h4>We need a bit more info to keep you posted on this event. </h4> 	
				<p><em>Already a member? <a href="{% url 'django.contrib.auth.views.login' %}">Login instead</a></em></p>
				<div id="new-user-form-errors"></div>
				<form id="new-user-form" class="form-horizontal">
					<div class="form-group">
						<span class="col-sm-3">
						{{ new_user_form.first_name.label_tag }}
						</span>
						<span class="col-sm-9">
						{{ new_user_form.first_name }}
						{{ new_user_form.first_name.errors }}
						</span>
					</div>
					<div class="form-group">
						<span class="col-sm-3">
						{{ new_user_form.last_name.label_tag }}
						</span>
						<span class="col-sm-9">
						{{ new_user_form.last_name }}
						{{ new_user_form.last_name.errors }}
						</span>
					</div>
					<div class="form-group">
						<span class="col-sm-3">
						{{ new_user_form.username.label_tag }}
						</span>
						<span class="col-sm-9">
						{{ new_user_form.username }}
						{{ new_user_form.username.errors }}
						</span>
					</div>
					<div class="form-group">
						<span class="col-sm-3">
						{{ new_user_form.email.label_tag }}
						</span>
						<span class="col-sm-9">
						{{ new_user_form.email }}
						{{ new_user_form.email.errors }}
						</span>
					</div>
					<div class="form-group">
						<span class="col-sm-3">
						{{ new_user_form.password1.label_tag }}
						</span>
						<span class="col-sm-9">
						{{ new_user_form.password1 }}
						{{ new_user_form.password1.errors }}
						</span>
					</div>
					<div class="form-group">
						<span class="col-sm-3">
						{{ new_user_form.password2.label_tag }}
						</span>
						<span class="col-sm-9">
						{{ new_user_form.password2 }}
						{{ new_user_form.password2.errors }}
						</span>
					</div>
					<div class="form-group">
						<div class="col-sm-12">
							<div class="checkbox">
								<label for="email-notifications">
									<input id="id_email_notifications" type="checkbox" name="email-notifications" false> Sign up for weekly event emails?
								</label>
							</div>
							<div class="text-muted">We won't send you any other emails unless you ask for them!</div>
						</div>
					</div>
					<input class="btn btn-default" type="submit" value="Submit RSVP">
				</form>
			</div>
		</div>
	</div>
	</div>


	{% if messages %}
	<div class="messages">
		{% for message in messages %}
		<div class="alert alert-info">
			<button type="button" class="close" data-dismiss="alert">×</button>
			<div {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message|safe }}</div>
		</div>
		{% endfor %}
</div>
	{% endif %}

	{% comment %} this area has an if statement and only displays if the event is not live {% endcomment %}
	<div id="event-status-area">
		{% include 'snippets/event_status_area.html' %}
	</div>

	{% if event.status == 'live' and event.private %}
		<div class="text-danger event-status">
			<span class="glyphicon glyphicon-star"></span> This event is viewable to those with the link.
		</div>
	{% endif %}


	<h1 class="event-detail-title">{{ event.title|title }}</h1> 
	{% if user_is_organizer %}
		<a id="event-edit-link" class="thirtypx-spacer-left" href="edit/">edit</a>
	{% endif %}
	<div class="event-time"> 
	{% with event.start|date as start_date %}
	{% with event.end|date as end_date %}
		<span class="event-date-day pull-left"> {{ event.start|date:'D'}}</span>
		<span class="event-date-month pull-left">{{ event.start|date:'b'|title}}</span>
		<span class="event-date-day pull-left"> {{ event.start|date:'j'}}</span>
		<span class="event-date-time pull-left">{{ event.start|date:'f A'}}</span>
		<span class="event-date-separator pull-left"><em>until</em></span>
		{% if start_date != end_date %}
		<span class="event-date-day pull-left"> {{ event.end|date:'D'}}</span>
		<span class="event-date-month pull-left">{{ event.end|date:'b'|title}}</span>
		<span class="event-date-day pull-left"> {{ event.end|date:'j'}}</span>
		{% endif %}
		<span class="event-date-time pull-left">{{ event.end|date:'f A'}}</span>
		<span class="event-location">, {{event.location }}</span>
	{% endwith %}
	{% endwith %}
	</div>

	<div class="col-md-8">
		<div class="row"> <img class="event-detail-img img-rounded" src="{{ MEDIA_URL }}{{ event.image }}" /></div>

		{% with event.organizers.get_query_set as organizers %}
		<h3>Organized by 
			{% for o in organizers %}
			<a href="{% url 'user_detail' o.username %}">{{ o.first_name }} {{o.last_name}}</a>{% if not forloop.last %}, {% endif %}
			{% endfor %}
		</h3>
		{% endwith %}
		{{ event.description|safe|linebreaks }}
	</div>

	<div class="col-md-4" id="rsvp-info">
		{% include 'snippets/rsvp_info.html' %}
	</div>

	{% if user_is_organizer %}
	<div class="col-md-12" id="organizer-notes">
		<hr>
		<h4>Organizer Notes</h4>
		<p>{{event.organizer_notes|default:"No notes"}}</p>
	</div>
	{% endif %}

</div>

{% if event.status == 'live' and not event.private %}
<div class="row">
<div class="col-md-2 col-md-offset-5" id="facebook-share-link">
	<a href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2F{{domain}}{% url 'gather_view_event' event.location.slug event.id event.slug %}" target="_blank"> Share on Facebook </a>
</div>
</div>
{% endif %}

{% endblock %}

{% block extrajs %}
<script>

	$("#new-user-form").submit(function(event) {
		form_data = $("#new-user-form").serialize();
		form_data = form_data + '&csrfmiddlewaretoken=' + '{{ csrf_token }}';
		request = $.ajax({ 
			data: form_data,	
			type: "POST",
			url: "{% url 'gather_rsvp_new_user' location.slug event.id event.slug %}"
		});

		request.done(function(msg) {
			if (msg.length > 0) {
				data = JSON.parse(JSON.parse(msg));
				if (data.errors) {
					console.log("errors");
					errors = data.errors;
					error_html = "<div class='text-danger'>There were errors in the form:</div>";
					for (var k in errors) {
						error_html += '<div class="text-danger">' + k + ': ' + errors[k] + '</div>';
					}
					console.log(error_html);
					$("#new-user-form-errors").html(error_html);
				} else {
					console.log("shouldn't be here...");
				} 
			} else {
				console.log("success");
				location.reload();
			}
		});

		request.fail(function(msg) {
			$("#attendance-message").html('<span class="bg-danger">Oops, there was a problem. Please try again.</span>')
		});

		event.preventDefault();
	});

	$("#approve-for-publication").click(function() {
		request = $.ajax({ 
			data: {
				'csrfmiddlewaretoken': '{{ csrf_token }}'
			},	
			type: "POST",
			url: "{% url 'gather_event_approve' location.slug event.id event.slug %}"
		});
		request.done(function(msg) {
			$("#event-status-area").html(msg);
		});

		request.fail(function(msg) {
			$("#event-status-area").html('<span class="text-danger">Oops, there was a problem. Please try again.</span>')
		});

		event.preventDefault();
	});

	$("#publish-event").click(function() {
		request = $.ajax({ 
			data: {
				'csrfmiddlewaretoken': '{{ csrf_token }}'
			},	
			type: "POST",
			url: "{% url 'gather_event_publish' location.slug event.id event.slug %}",
		});

	});

</script>
{% endblock %}

gather/templates/gather_events_admin_needing_review.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}

<div class="text-danger" id="event-admin-heads-up"><span class="glyphicon glyphicon-exclamation-sign"></span> Only events in the future are shown here</div>

<ul class="nav nav-tabs" id="event-list-tabs">
	<li class="active"><a href="#pending" data-toggle="tab">Waiting Approval</a></li>
	<li><a href="#feedback" data-toggle="tab">Seeking Feedback</a></li>
</ul>

<div class="tab-content">

	<div id="pending" class="tab-pane active fade in">
		{% for event in events_pending %}
			{% include 'snippets/event-list-compact.html' %}
		{% endfor %}
	</div>
	<div id="feedback" class="tab-pane fade">
		{% for event in events_under_discussion %}
			{% include 'snippets/event-list-compact.html' %}
		{% endfor %}
	</div>

</div>


{% endblock %}

gather/templates/gather_events_list.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}

<div class="row">
	<h1>{{ page_title|title }}</h1>
</div>

{% block createlink %}
<div id="event_create_link">
	[ <a href="{% url 'gather_create_event' location.slug %}">Add Event</a> ]
</div>
{% endblock %}

{% for event in events %}

<div class="row">
	<div class="col-md-12 event">
		<div class="col-md-1 date"><span class="day">{{ event.start|date:'j'}}</span>{{ event.start|date:'b'|title}}</div>
		<div class="col-md-11">
			<a href="{% url 'gather_view_event' location.slug event.id event.slug %}"> <h3 class="event-title">{{ event.title}}</h3> </a>
			<div class="col-md-4">
				<img class="event-preview-img-thumb" src="{{ event.image.url }}"/>
			</div>
			<div class="col-md-7"> 
				<div class="event-list-time">{{ event.start }} - {{ event.end }}</div>
				<div>{{ event.description|safe|linebreaks }} </div>
			</div>
		</div>
	</div>
</div>

{% empty %}

<p class="lead">No upcoming events! Why not <a href="{% url 'gather_create_event' location.slug %}">propose one?</a></p>	
{% endfor %}


<div class="pagination">
    <span class="step-links">
        {% if events.has_previous %}
            <a href="?page={{ events.previous_page_number }}">previous</a>
        {% endif %}	

        <span class="current">
            Page {{ events.number }} of {{ events.paginator.num_pages }}
        </span>

        {% if events.has_next %}
            <a href="?page={{ events.next_page_number }}">next</a>
        {% endif %}
    </span>
</div>

{% endblock %}